version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: web.docker
        volumes:
            - ./www:/var/www
        ports:
            - "8000:80"
        links:
            - app
        container_name: web
    app:
        build:
            context: ./
            dockerfile: app.docker
        volumes:
            - ./www:/var/www
        links:
            - mysql
            - redis
        container_name: app
    mysql:
        restart: always
        image: mysql:latest
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=laraveltest"
        ports:
            - "3306:3306"
        container_name: mysql
    redis:
        restart: always
        image: redis:latest
        volumes:
            - ./redis:/data
        ports:
            - "6379:6379"
        container_name: redis
        command: redis-server --appendonly yes

